spring:
  application:
    name: course-catalog-service
  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/courses
#    url: jdbc:postgresql://localhost:5432/courses
    username: postgres
    password: postgres
  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
message: Hello from default profile

---
spring:
  config:
    activate:
      on-profile: prod
message: Hello from prod profile